import type { NextPage } from "next";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import styles from "../styles/Home.module.css";
import Header from "../components/sharedComponents/header/header";
import SidebarMenu from "../components/sharedComponents/sidebar/sidebar";
import Footer from "../components/sharedComponents/footer/footer";
import FloatButton from "../components/sharedComponents/floatButton/floatButton";
import RightSidebar from "../components/sharedComponents/rightSidebar/rightSidebar";

const Home: NextPage = () => {
  return (
    <div className={`${"container"}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${"row"}`}>
        <div className={`${"col-2"}`}>
          <SidebarMenu></SidebarMenu>
        </div>
        <div className={`${"col-10"} ${styles.headerContainer}`}>
          <Header></Header>
        </div>
      </div>
      <div className={`${"row"} ${styles.footerPosition}`}>
        <Footer></Footer>
      </div>
      <FloatButton></FloatButton>
      <RightSidebar></RightSidebar>
    </div>
  );
};

export default Home;
