import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/sharedComponents/header/header";
import SidebarMenu from "../components/sharedComponents/sidebar/sidebar";
import Footer from "../components/sharedComponents/footer/footer";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${"row"}`}>
        <div className={`${"col-2"}`}>
          <SidebarMenu></SidebarMenu>
        </div>
        <div className={`${"col-10"}`}>
          <Header></Header>
        </div>
      </div>
      <div className={`${"row"} ${styles.footerPosition}`}>
        <Footer></Footer>
      </div>
    </div>
  );
};

export default Home;
